# This configuration file updates the default configuration file
# See https://github.com/searxng/searxng/blob/master/searx/limiter.toml

[botdetection.ip_limit]
# activate advanced bot protection
# enable this when running the instance for public usage on the internet
link_token = false
filter_link_local = true #deactivate the bot protection for local addresses, which permits you to use the API mode locally without issues and a simplified security.
